DLS-9060 - Partnership URL fix
hmrc/fh-registration-frontend pull request #477
Opened 2023-10-25 12:55 UTC by jackwillett1

2023-10-26 05:25 UTC, gjstirling commented on it/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersEnterRegistrationOfficeAddressControllerISpec.scala
If using TestClient .drop() and baseUrl is not needed on route. 

Is it worth converting files to use only one or the other ?

2023-10-26 05:29 UTC, gjstirling commented on test/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersPartnershipCompanyRegistrationNumberControllerSpec.scala
Use val for page like others ?

2023-10-26 05:30 UTC, gjstirling requested changes
See comments

2023-10-30 10:41 UTC, BackRowOla approved these changes

2023-10-30 10:48 UTC, merged