DLS-10601: User able to submit same VAT registration for company officer as business registering for FHDDS (WCAG)
hmrc/fh-registration-frontend pull request #589
Opened 2024-08-09 15:09 UTC by drewmiley

2024-08-09 15:47 UTC, drewmiley commented
TODO: Indent company_officers template. Add unit tests

2024-08-15 12:05 UTC, Chrissystk requested changes
Good work Drew. I have left a few comments mainly around writing things slightly different. Let me know if you have any questions.

2024-08-15 12:05 UTC, Chrissystk commented on app/uk/gov/hmrc/fhregistrationfrontend/controllers/FormPageController.scala
> +
Continuing on from the previous comment I think this function can be made more concise and clearer if written like this:

```
def saveCompanyOfficers(sectionId: Option[String]): Action[AnyContent] =
    pageAction("companyOfficers", sectionId).async { implicit request =>
      request
        .page[ListWithTrackedChanges[CompanyOfficer]]
        .parseFromRequest(
          pageWithErrors => Future successful renderForm(pageWithErrors, true),
          page => {
            val pageData: ListWithTrackedChanges[CompanyOfficer] = page.data.get
            val companyOfficersPageData = pageData.values.toList
            val sectionIndex = sectionId.map(_.toInt - 1).getOrElse(0)
            def vatNumberIsUnique(vatNumber: String): Boolean = {
              request.isVatNumberUnique(companyOfficersPageData, vatNumber, sectionIndex)
            }
            CompanyOfficer.getVatNumber(companyOfficersPageData(sectionIndex)) match {
              case Some(vatNumber) if !vatNumberIsUnique(vatNumber) =>
                val companyOfficersPage = new InjectedPage(views)
                  .companyOfficersPage.copy(value = pageData, index = sectionIndex)

                Future successful BadRequest(
                  companyOfficersPage.renderWithFormError(
                    CompanyOfficersForm.withError("vatRegistration", "error.vatAlreadyUsed"),
                    request.bpr,
                    request.journey.navigation(request.lastUpdateTimestamp, request.page)
                  )(request, request2Messages(request), appConfig)
                )
              case _ => saveSuccessfully(page)
            }
          }
        )
    }
```

As you can see I only check the vatNumber if a vatNumber is present here.

2024-08-19 18:40 UTC, Chrissystk approved these changes

2024-08-20 09:48 UTC, merged